version:  "3.0"
services:
  mysql:
    container_name: mysqlServer
    image: mysql:latest
    ports:
      - 3306:3306
    volumes:
      - ./data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: dbname1
      MYSQL_USER: dbuser
      MYSQL_PASSWORD: dbpass

  mysql2:
    container_name: mysqlServer2
    image: mysql:latest
    ports:
      - 3307:3306
    volumes:
      - ./data2:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: dbname2
      MYSQL_USER: dbuser
      MYSQL_PASSWORD: dbpass